// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bidgnwwibvowwhdgcwan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZGdud3dpYnZvd3doZGdjd2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5MjczNTMsImV4cCI6MjA4MTUwMzM1M30.ATnQeYvDqKEv9WDndmZPrBQG0zZVVPMZouSkx2SQwek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);